### ISSUE TITLE
sqlite schema

### ISSUE THREAD

**Issue by ivarmedi** [dhtech/dhmon#12]
Hello,

We're looking into using the snmpcollector to monitor our switches. I have the snmpcollector installed and ready, but noted that some documentation around the ipplan is outdated. 

In the examples it's a text file, but in reality it seems to be an sqlite database. Is there a schema available for the database? I managed to piece some rudimentary setup together based on the query used in `supervisor.py`, but alas.

**Comment by SoundGoof** [comment]
hi, we have https://github.com/dhtech/ipplan2sqlite that does the conversion between the 2, we have our ipplan.txt version controlled and the ipplan2sqlite is done in a pre-hook

**Comment by ivarmedi** [comment]
Thank you for the quick reply! That made everything a lot easier :)
